Repository CSID-DGU/2020-2-OSSP-CP-17woljang-9, pull requests merged in 2020-11, with the labels that each got.

#24 음소거 기능 추가
  OMPYTRIS/__pycache__/mino.cpython-37.pyc
  OMPYTRIS/assets/vector/sound_off_button.png
  OMPYTRIS/assets/vector/sound_on_button.png
  OMPYTRIS/ompytris.py
  PYTRIS/__pycache__/mino.cpython-37.pyc
  PYTRIS/leaderboard.txt
Labels: 공통, 제안

#26 rainbow 보너스 점수 구현
  OMPYTRIS/__pycache__/mino.cpython-39.pyc
  OMPYTRIS/assets/vector/rainbow.png
  OMPYTRIS/ompytris.py
  PYTRIS/__pycache__/mino.cpython-39.pyc
  PYTRIS/pytris.py
Labels: 공통, 수정

#27 pvp sidebar 재정비
  OMPYTRIS/ompytris.py
Labels: PVP, 수정

#31 변수정리, 함수2p삭제, 하드드롭,pvp게임, pvp sidebar오류수정
  OMPYTRIS/leaderboard.txt
  OMPYTRIS/ompytris.py
Labels: PVP, 수정

#34 음소거 기능 추가 수정
  OMPYTRIS/assets/vector/allmute_button.png
  OMPYTRIS/assets/vector/default_button.png
  OMPYTRIS/ompytris.py
Labels: 공통
